Fix the result from .index() replacement
HubSpot/youmightnotneedjquery pull request #224
Opened 2020-06-26 07:22 UTC by simeydotme

I found when attempting to use the `.index()` replacement that the index was off by 1.
The error was because the `do {}` part of the loop was executing the `i++` before the condition was evaluated meaning the result is always at-least `1`. 

This is wrong as the first element should have an index of `0`.

Here's a JSFiddle showing the before/after and with the jQuery version as a reference.
https://jsfiddle.net/yck52avu/1/

2021-09-06 15:17 UTC, Abbondanzo reviewed
Edit: see below

2021-09-06 15:47 UTC, Abbondanzo requested changes
Great catch. Could you make these changes in the [`comparisons/elements/index`](https://github.com/HubSpot/youmightnotneedjquery/tree/gh-pages/comparisons/elements/index) folder? This file is automatically generated

2021-09-10 16:46 UTC, simeydotme commented
I've modified the commit so the changes are in the source files, @Abbondanzo  ... sorry about that! :)

2021-09-10 20:42 UTC, Abbondanzo approved these changes
All good and thanks! My plan is to remove the generated files from the repo outright soon so we can avoid any confusion in the future

2021-09-10 20:42 UTC, merged